servers:
  - type: "socks5"
    enabled: true
    host: 127.0.0.1
    port: 5000
    username: "user"
    password: "password"
    protocol: "tcp"

  - type: "socket"
    enabled: true
    host: 127.0.0.1
    port: 5001
    handler: "echo"

  - type: "ssl-socket"
    enabled: true
    host: 127.0.0.1
    port: 5002
    certfile: "server-chain.pem"
    keyfile: "server-key.pem"
    cafile: "ca.pem"
    handler: "echo"
    minTlsVersion: "TLSv1.2"
    maxTlsVersion: "TLSv1.3"
    # Optional: Specify the cipher suites to use (applies only to TLSv1.2 or earlier)
    # Note: TLSv1.3 does not allow specifying cipher suites
    # https://pkg.go.dev/crypto/tls#pkg-constants
    # test example:
    # openssl s_client -connect 127.0.0.1:5002 -cert client.pem -key client-key.pem -CAfile ca.pem -tls1_2 -cipher TLS_RSA_WITH_AES_128_CBC_SHA
    cipherSuites:
      - "TLS_RSA_WITH_AES_128_CBC_SHA"
      - "TLS_RSA_WITH_AES_256_CBC_SHA"
      - "TLS_RSA_WITH_AES_128_GCM_SHA256"
